image: docker:dind

stages:
  - release
  - latest
variables:
  MANDELBULBER_VERSION: "2.25"
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
# dockerize:
#   stage: docker
#   image: docker:dind
#   only:
#     - master
#     - dev
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#   script:
#     - docker build --build-arg VERSION=${MANDELBULBER_VERSION} -t $CI_PROJECT_NAME .
#     - docker save $CI_PROJECT_NAME:latest | gzip > $CI_PROJECT_NAME.tar.gz
#     - docker tag $CI_PROJECT_NAME registry.gitlab.com/mandelbulber/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
#     - docker push registry.gitlab.com/mandelbulber/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
#   artifacts:
#     paths:
#       - $CI_PROJECT_NAME.tar.gz

# dockerize-and-tag:
#   stage: docker
#   image: docker:dind
#   services:
#     - docker:dind
#   only:
#     - branches
#   before_script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#   script:
#     - sed -i 's/\(version=\)\(.*\)/\1"'$CI_COMMIT_TAG'"/' Dockerfile
#     - docker build -t $CI_PROJECT_NAME .
#     - docker save $CI_PROJECT_NAME:latest | gzip > $CI_PROJECT_NAME.tar.gz
#     - docker tag $CI_PROJECT_NAME registry.gitlab.com/mandelbulber/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
#     - docker push registry.gitlab.com/mandelbulber/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
#   artifacts:
#     paths:
#       - $CI_PROJECT_NAME.tar.gz

release:
  stage: release
  image: docker:dind
  only:
    - master
    - schedules
  services:
    - docker:dind
  script:
    - docker build --build-arg VERSION=${MANDELBULBER_VERSION} -t $CI_PROJECT_NAME:${MANDELBULBER_VERSION} .
    - docker save $CI_PROJECT_NAME:${MANDELBULBER_VERSION} | gzip > $CI_PROJECT_NAME.tar.gz
    - docker tag $CI_PROJECT_NAME:${MANDELBULBER_VERSION} registry.gitlab.com/mandelbulber/$CI_PROJECT_NAME:${MANDELBULBER_VERSION}
    - docker push registry.gitlab.com/mandelbulber/$CI_PROJECT_NAME:${MANDELBULBER_VERSION}
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_SECRET
    - docker tag $CI_PROJECT_NAME:${MANDELBULBER_VERSION} $DOCKERHUB_USER/$CI_PROJECT_NAME:latest
    - docker push $DOCKERHUB_USER/$CI_PROJECT_NAME:latest

latest-gitlab:
  stage: latest
  image: docker:dind
  dependencies:
    - release
  services:
    - docker:dind
  only:
    - master
    - schedules
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

latest-dockerhub:
  stage: latest
  image: docker:dind
  dependencies:
    - release
  services:
    - docker:dind
  only:
    - master
    - schedules
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE $DOCKERHUB_USER/$CI_PROJECT_NAME:latest
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_SECRET
    - docker push $DOCKERHUB_USER/$CI_PROJECT_NAME:latest
