image: docker:dind

stages:
  - release
  - latest
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
release:
  stage: release
  image: docker:dind
  only:
    - master
    - schedules
  #services:
  #  - docker:dind
  before_script:
    - apk add jq
    - apk add curl
    - apk add bash
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_SECRET
    - chmod +x release.sh
    - bash ./release.sh
